# -*- coding: utf-8 -*-
"""
CapsStream Database Module (backend.db)
Modularized database package maintaining 100% backward compatibility.
"""

from .connection import (
    DB_PATH,
    TEMPLATE_DB_PATH,
    DATA_DIR,
    get_conn,
    release_conn,
    _apply_pragmas,
)

from .schema import (
    init_db,
)

from .media import (
    is_drive_mounted,
    is_item_mounted,
    enrich_mounted,
    get_disabled_path_roots,
    is_file_path_disabled,
    is_item_disabled,
    get_all_sources_for_media,
    resolve_best_media,
    get_best_media_source,
    format_file_size_bytes,
    get_media_quality_options,
    enrich_mounted_list,
    get_all_media,
    get_media_by_id,
    delete_media_by_id,
    delete_media_by_tmdb,
    delete_media_by_title_and_type,
    update_skip_timestamps,
    get_media_by_tmdb,
    search_media,
    get_unique_shows,
    get_recently_added,
    get_top_rated,
    get_by_genre,
    get_random_pick,
    get_hero_featured,
    get_all_genres,
    upsert_media,
    update_duration,
    get_unmatched,
)

from .profiles import (
    get_all_profiles,
    get_profile,
    create_profile,
    update_profile,
    reorder_profiles,
    delete_profile,
    verify_pin,
    hash_pin,
    verify_pin_raw,
    get_kids_override_map,
    list_kids_overrides,
    set_kids_override,
    remove_kids_override,
)

from .playback import (
    get_progress,
    save_progress,
    delete_progress,
    get_continue_watching,
    get_profile_recommendations,
    get_similar_media,
)

from .achievements import (
    ACHIEVEMENTS,
    KIDS_ACHIEVEMENTS,
    ACTION_TO_KIDS_ACHIEVEMENTS,
    get_profile_catalog,
    unlock_achievement,
    check_and_unlock_achievements,
    get_profile_achievements,
)

from .stats import (
    get_profile_watch_stats,
    get_profile_wrapped_analytics,
)

from .collections import (
    get_favorites,
    toggle_favorite,
    is_favorite,
    get_collections,
    create_collection,
    delete_collection,
    add_to_collection,
    remove_from_collection,
)

from .playlists import (
    get_playlists,
    get_playlist,
    create_playlist,
    update_playlist,
    delete_playlist,
    add_to_playlist,
    remove_from_playlist,
    reorder_playlist,
    is_media_in_playlist,
)

__all__ = [
    "DB_PATH",
    "TEMPLATE_DB_PATH",
    "DATA_DIR",
    "get_conn",
    "release_conn",
    "_apply_pragmas",
    "init_db",
    "is_drive_mounted",
    "is_item_mounted",
    "enrich_mounted",
    "get_disabled_path_roots",
    "is_file_path_disabled",
    "is_item_disabled",
    "get_all_sources_for_media",
    "resolve_best_media",
    "get_best_media_source",
    "format_file_size_bytes",
    "get_media_quality_options",
    "enrich_mounted_list",
    "get_all_media",
    "get_media_by_id",
    "delete_media_by_id",
    "delete_media_by_tmdb",
    "delete_media_by_title_and_type",
    "update_skip_timestamps",
    "get_media_by_tmdb",
    "search_media",
    "get_unique_shows",
    "get_recently_added",
    "get_top_rated",
    "get_by_genre",
    "get_random_pick",
    "get_hero_featured",
    "get_all_genres",
    "upsert_media",
    "update_duration",
    "get_unmatched",
    "get_all_profiles",
    "get_profile",
    "create_profile",
    "update_profile",
    "reorder_profiles",
    "delete_profile",
    "verify_pin",
    "hash_pin",
    "verify_pin_raw",
    "get_kids_override_map",
    "list_kids_overrides",
    "set_kids_override",
    "remove_kids_override",
    "get_progress",
    "save_progress",
    "delete_progress",
    "get_continue_watching",
    "get_profile_recommendations",
    "get_similar_media",
    "ACHIEVEMENTS",
    "KIDS_ACHIEVEMENTS",
    "ACTION_TO_KIDS_ACHIEVEMENTS",
    "get_profile_catalog",
    "unlock_achievement",
    "check_and_unlock_achievements",
    "get_profile_achievements",
    "get_profile_watch_stats",
    "get_profile_wrapped_analytics",
    "get_favorites",
    "toggle_favorite",
    "is_favorite",
    "get_collections",
    "create_collection",
    "delete_collection",
    "add_to_collection",
    "remove_from_collection",
    "get_playlists",
    "get_playlist",
    "create_playlist",
    "update_playlist",
    "delete_playlist",
    "add_to_playlist",
    "remove_from_playlist",
    "reorder_playlist",
    "is_media_in_playlist",
]
